### ISSUE TITLE
Not Responding error

### ISSUE THREAD

**Issue by hamza00789** [realthunder/FreeCAD_assembly3#882] opened 2021-10-18 14:25 UTC
OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.1015.24301 +4280 (Git)
Build type: Release
Branch: LinkDaily
Hash: 556c87868ea46796242156e9f73eae98259794b7
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/United States (en_US)

when i command a PartWorkBanch Create Shape from mesh
Software is Not Responding error
![1](https://user-images.githubusercontent.com/92737149/142691904-6c9afb33-2115-4c0d-916c-1d7b45812431.jpg)
![2](https://user-images.githubusercontent.com/92737149/142691925-1734f71d-9f22-4ba4-b832-ed42baa8af3e.jpg)
File  
[STL.file.zip](https://github.com/realthunder/FreeCAD_assembly3/files/7572937/STL.file.zip)

**Comment by realthunder** [comment] 2021-10-19 00:28
Which operation did you perform? I did find any command to 'Create shape from mesh'.

**Comment by hamza00789** [comment] 2021-11-19 20:51
> Which operation did you perform? I did find any command to 'Create shape from mesh'.

**Comment by hamza00789** [comment] 2021-11-19 20:52
> Which operation did you perform? I did find any command to 'Create shape from mesh'.

**Comment by hamza00789** [comment] 2021-11-19 21:18
> Which operation did you perform? I did find any command to 'Create shape from mesh'.

The solution to my problem is in this version of FreeCad. 
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.26155 (Git)
Build type: Release
Branch: master
Hash: 0926a4148bcff11249fd4f56bc30256102ffe105
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/United States (en_US) 
![1](https://user-images.githubusercontent.com/92737149/142692706-76c8d963-722d-4582-8564-db0185649d47.jpg)
![2](https://user-images.githubusercontent.com/92737149/142692719-a6c17a7c-52c4-40ca-933b-77287e53b8c2.jpg) 

But that doesn't work in this version of FreeCad. 
OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.1015.24301 +4280 (Git)
Build type: Release
Branch: LinkDaily
Hash: 556c87868ea46796242156e9f73eae98259794b7
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/United States (en_US) 
![1](https://user-images.githubusercontent.com/92737149/142692795-9e6e747e-1f36-4b0d-ab3c-2fa6faaa27a1.jpg)
![2](https://user-images.githubusercontent.com/92737149/142692803-091431fd-8d74-42a1-b6ed-d6b9bad4f0e6.jpg) 
 
Can you tell me why?

**Comment by realthunder** [comment] 2021-11-20 06:17
Should be working in the next release which merges with upstream 0.20

**Comment by luzpaz** [comment] 2022-01-12 04:21
@hamza00789 please retest

**Comment by hamza00789** [comment] 2022-01-12 11:28
> @hamza00789 please retest

OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2022.111.30764 (Git)
Build type: Release
Branch: LinkDaily
Hash: ef3092bcbca5475eff4eb7ff7933eb3e9bbbe4b9
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.6.0
Locale: English/United States (en_US)             

There are some issues with the new release. Now even my file is not being imported. Freecad shuts down when I try to import a file.          


https://user-images.githubusercontent.com/92737149/149132004-0de1f5ba-eb1e-4b5f-b099-6fb67537a449.mp4

**Comment by luzpaz** [comment] 2022-01-12 19:20
Thanks for the follow-up. BTW, please use 'Crash' instead of 'shuts down'.

**Comment by realthunder** [comment] 2022-01-17 06:16
@hamza00789, the crash on 01.01 release is a duplicate of #1024. I'll close this first.

**Closed by realthunder** 2022-01-17 06:16 UTC
Labels: bug, waiting next release
