### ISSUE TITLE
Feature proposal: Add a refine checkbox to dialogs of additive, substractive and transformation tools

### ISSUE THREAD

**Issue by Rabbit-sk** [realthunder/FreeCAD_assembly3#413] opened 2021-01-11 12:20 UTC
Dear Realthunder,

I was thinking of adding the refine check box to the dialogs of all additive and subtractive features (or where it is applicable). This could speed up the work. 

The expected behavior of this option would be:
1. Set parameters of a feature and check the refine checkbox
2. Confirm creation of a feature
3. New shape is created and afterwards Refine will be set to true
4. Later it will be possible in data tab to set refine to false

Do you think it would be good to add this option to the dialog?

Regards

**Comment by realthunder** [comment] 2021-01-16 07:46
What about the options below? Is that what you are look for?

![Screenshot from 2021-01-16 15-44-22](https://user-images.githubusercontent.com/1207888/104806369-e8e5e180-5811-11eb-9d70-902d5aae12ad.png)

**Comment by Rabbit-sk** [comment] 2021-01-16 08:59
😃 yes! Thank you!
That was what I was looking for:
![obrázok](https://user-images.githubusercontent.com/74265320/104807730-4ca3e680-57e1-11eb-9930-bc3de0e79e46.png)

**Comment by realthunder** [comment] 2021-01-16 09:05
Be aware that there is come inefficiency in my topo naming encoding regarding this refine operation. It works but the file size may increase rapidly with refine. This has already been fixed in one of my other branch, but it's quite a big change. I'll release it later with a different prefix than 'Daily', or maybe promote the current 'Daily' as stable release. Meanwhile, it will be better to only refine in the last few modeling steps.

**Comment by Rabbit-sk** [comment] 2021-01-16 11:04
One more little thing. The text of this setting:
![obrázok](https://user-images.githubusercontent.com/74265320/104810040-6e599980-57f2-11eb-8428-47a9384a8dee.png)
could be changed to something like this:
`Automatically refine model after sketch or face based operation`
because this setting has effect also if a face is used:

https://user-images.githubusercontent.com/74265320/104810083-cee8d680-57f2-11eb-82b4-87682733f8b4.mp4

**Comment by Rabbit-sk** [comment] 2021-01-16 12:01
> Be aware that there is come inefficiency in my topo naming encoding regarding this refine operation. It works but the file size may increase rapidly with refine. 

> Meanwhile, it will be better to only refine in the last few modeling steps.

Good to know. 

> This has already been fixed in one of my other branch, but it's quite a big change. I'll release it later with a different prefix than 'Daily', or maybe promote the current 'Daily' as stable release. 

Good idea! I think that this branch deserves a stable release. So far from my experience, I also think that version 2021.0112 is suitable for that. I keep some older daily releases in case there is an issue in the latest release, but new user can download only latest one. It will be good to have a stable release available and can test changes in another release.

**Comment by Rabbit-sk** [comment] 2021-01-26 09:51
> 
> 
> One more little thing. The text of this setting:
> ![obrázok](https://user-images.githubusercontent.com/74265320/104810040-6e599980-57f2-11eb-8428-47a9384a8dee.png)
> could be changed to something like this:
> `Automatically refine model after sketch or face based operation`
> because this setting has effect also if a face is used:
> 2021-01-16.11-55-54.mp4

Do you think that renaming this setting matters? If not, I would like to close this issue, because my first question is solved.

**Comment by realthunder** [comment] 2021-01-27 08:21
I just checked code. The `refine model after sketch-based operation` is actually used exclusively by features in PartDesign, not just sketch-based, while the other `refine` option is for features in Part workbench.

**Closed** 2021-01-29 09:35 UTC

**Comment by Rabbit-sk** [comment] 2021-02-10 11:53
> Be aware that there is come inefficiency in my topo naming encoding regarding this refine operation. It works but the file size may increase rapidly with refine. This has already been fixed in one of my other branch, but it's quite a big change. I'll release it later with a different prefix than 'Daily', or maybe promote the current 'Daily' as stable release. Meanwhile, it will be better to only refine in the last few modeling steps.

Is this big change already included in latest daily build, or it is still better to only refine in the last few modeling steps?

**Comment by realthunder** [comment] 2021-02-12 03:27
Unfortunately, no. It's still in my other branch. I'll try to release it this month.

**Comment by Rabbit-sk** [comment] 2021-02-12 09:00
Okay, then please mention it in the release notes :) Thank you for improving FreeCAD!

**Comment by ceremcem** [comment] 2021-02-14 17:58
(Related to (or duplicate of): https://github.com/realthunder/FreeCAD_assembly3/issues/235)
