### ISSUE TITLE
AppImage will not run due to system C++ library mismatch

### ISSUE THREAD

**Issue by svenvvv** [realthunder/FreeCAD_assembly3#763] opened 2021-07-31 08:28 UTC
Running the 17.07 daily AppImage results in the following output:
```
FreeCAD 0.19, Libs: 2021.717R24301 +3842 (Git)
Loading Assembly4 WorkBench
Sheet Metal workbench loaded
libGL error: MESA-LOADER: failed to open radeonsi: /tmp/.mount_FreeCAY1FDdi/usr/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/radeonsi_dri.so) (search paths /usr/lib/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open radeonsi: /tmp/.mount_FreeCAY1FDdi/usr/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/radeonsi_dri.so) (search paths /usr/lib/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast: /tmp/.mount_FreeCAY1FDdi/usr/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/swrast_dri.so) (search paths /usr/lib/dri)
libGL error: failed to load driver: swrast
[...]
/tmp/.mount_FreeCAOJoDx4/AppRun: line 46: 12120 Aborted                 (core dumped) "$PREFIX/bin/$name" "$@"
```

The crashes started after a system update.
This crash also takes place previous AppImage releases (tried `20210531`).
It used to work before the system update.  

OS: Arch Linux
gcc-libs (contains `libstdc++`): 11.1.0
glibc: 2.33
mesa: 21.1.4

The AppImages previously worked with gcc-libs at version `10.x.x`.

Any other users facing the same problem can try fixing it by making the AppImage fall back to the system C++ libraries:

1. Unpack AppImage 
`./FreeCAD-asm3-Daily-Conda-Py3-Qt5-20210717-glibc2.12-x86_64.AppImage --appimage-extract`,
2. Remove the in-image C++ library
`rm squashfs-root/usr/lib/libstdc++.*`,
3. Repack AppImage
`appimagetool -v squashfs-root`.

**Comment by luzpaz** [comment] 2021-07-31 12:26
Duplicate of #671  
This was solved on FreeCAD Master. realthunder needs to trigger a new build of the appimage for this to be fixed.

**Closed by luzpaz** 2021-07-31 12:26 UTC
