### ISSUE TITLE
On dialogs buttons only clicks over the text take effect

### ISSUE THREAD

**Issue by tonilupi** [realthunder/FreeCAD_assembly3#503] opened 2021-03-07 19:17 UTC
Hi, first of all I want to thank you for the great effort you're making with your Linkbranch.

In my first contribution I want to show you this issue: On the buttons of the dialog boxes it is necessary to click on the texts for the action to be take in consideration.

![image](https://user-images.githubusercontent.com/36629167/110251421-9eb2ee00-7f80-11eb-904d-c8f8ba6bf538.png)

On red zone nothing happen when you press, only on green zone the pushing take effect.

**Comment by ceremcem** [comment] 2021-03-07 19:40
Duplicate of https://github.com/realthunder/FreeCAD_assembly3/issues/479

**Comment by tonilupi** [comment] 2021-03-07 20:06
> Duplicate of #479

Sorry for the inconvenience. Can I erase the issue or I must to close it?

**Comment by ceremcem** [comment] 2021-03-07 20:08
No problem. You can just close it.

**Closed** 2021-03-07 20:09 UTC
