### ISSUE TITLE
External geometry issue

### ISSUE THREAD

**Issue by hamza00789** [realthunder/FreeCAD_assembly3#938] opened 2021-11-22 16:27 UTC
External geometry Geometry is not complete. Or the geometry of the other side
![1](https://user-images.githubusercontent.com/92737149/142898237-47ba01dd-0079-4af0-8b11-8154b94da3dd.jpg)
![2](https://user-images.githubusercontent.com/92737149/142898272-79d7568f-9320-4503-ada7-45b0d97b7429.jpg)
![3](https://user-images.githubusercontent.com/92737149/142898286-b501a082-e709-4ee0-b1e4-68f9e25d1b97.jpg)
![4](https://user-images.githubusercontent.com/92737149/142898300-f03a29c1-8689-478d-b508-5b2423b9fdf0.jpg)     

OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.1015.24301 +4280 (Git)
Build type: Release
Branch: LinkDaily
Hash: 556c87868ea46796242156e9f73eae98259794b7
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/United States (en_US)

**Comment by bambukouk** [comment] 2021-11-23 10:15
see also #933

**Comment by bambukouk** [comment] 2021-11-23 13:56
my head is spinning :-)
is it closed or re-opened ....

**Comment by hamza00789** [comment] 2021-11-23 14:08
> my head is spinning :-) is it closed or re-opened ....

Sorry. It has been opened.

**Comment by bambukouk** [comment] 2021-11-23 15:57
Haven't got a clue :-(
@realthunder never replied so I don't even know whether he is doing anything about this one?
Hopefully he will surprise us (positively) as he often does :+1:

**Comment by realthunder** [comment] 2021-11-24 06:04
@bambukouk @hamza00789 Can you please post the files that have the problem? I've recently merged with upstream 0.20. So maybe the problem is solved. I'll check.

**Comment by bambukouk** [comment] 2021-11-24 08:29
@realthunder 
Thank you :+1: 
I have posted the file (plus additional explanations) in the original issue https://github.com/realthunder/FreeCAD_assembly3/issues/933#issuecomment-977643515 just in case it is separate from @hamza00789  issue?

**Comment by hamza00789** [comment] 2021-11-24 15:56
> @bambukouk @hamza00789 Can you please post the files that have the problem? I've recently merged with upstream 0.20. So maybe the problem is solved. I'll check.

[Bolt 2.1.zip](https://github.com/realthunder/FreeCAD_assembly3/files/7597051/Bolt.2.1.zip)

**Closed** 2021-11-30 03:51 UTC
