### ISSUE TITLE
Could not select center point

### ISSUE THREAD

**Issue by mwlandolsi** [realthunder/FreeCAD_assembly3#829] opened 2021-09-16 22:18 UTC
Hello,
a central point could not be selected when a symmetric constraint is set with the axis that passes through.

https://user-images.githubusercontent.com/76944804/133692875-3d0b2120-c8f3-424c-8d90-e335efe9b4c4.mp4

OS: Linux Mint 20.1 (X-Cinnamon/cinnamon)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.916.24301 +4152 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 7fd36f96f4db17db4f8d058eab22588cca8f9d5c
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.2
Locale: English/United States (en_US)

**Comment by realthunder** [comment] 2021-09-17 05:53
It's a duplicate of #824. The problem only occur on symmetry constraint.

**Closed** 2021-09-17 06:12 UTC
Labels: duplicate
