### ISSUE TITLE
Freecad freezes during startup, save and export (MAC user)

### ISSUE THREAD

**Issue by joanperelopez** [realthunder/FreeCAD_assembly3#717] opened 2021-07-07 17:48 UTC
freecad last version: 2021 6, 15

Freecad freezes several times during startup (beach ball). 
Freecad also freezes when I try to save or export (even the Mac is freezed). It seam something related to box dialog for the name of the file, directory, etc. The same happened with some older versions.

Thanks in advance

**Comment by thomasgi1** [comment] 2021-07-08 20:34
That behaviour is not specific to the asm3 branch. The main FC branch is affected too. The system freeze is caused by some misbehaving security checks performed by MacOS itself, when running unsigned software.
As a workaround you can self-sign your copy of FC as mentioned on the [Known OS specific issues](https://forum.freecadweb.org/viewtopic.php?f=3&t=30573) page of the FC forum. Please follow the instructions of the **Workaround 3** for the 2. MacOS issue **freezing for about a minute on MacOS Mojave (10.14)** on the page.

BR Tom

**Comment by luzpaz** [comment] 2021-08-03 10:13
Closing issue

**Closed by luzpaz** 2021-08-03 10:13 UTC
Labels: has workaround, macos, upstream
