### ISSUE TITLE
Recent files thumbnails broken

### ISSUE THREAD

**Issue by pgilfernandez** [realthunder/FreeCAD_assembly3#510] opened 2021-03-10 11:30 UTC
Since a few builds the Recent Files list thumbnails get broken each time I add a new build. Right now I'm using your last one, asm3-20210301.

This is the popup I get, one popup per thumbnail and every time I save a file (while the Start page is loaded, if not it doesn't happen):
<img width="688" alt="recents1" src="https://user-images.githubusercontent.com/5942369/110622837-48ba9200-819c-11eb-96a7-6200f78ce95e.png">

In the Recent List this is one example of what I get:
<img width="161" alt="recents2" src="https://user-images.githubusercontent.com/5942369/110622849-4fe1a000-819c-11eb-9591-0256a56237f4.png">

I don't know if it is something related with an accent (as you see in the last picture, my name is "Pablo Gil Fernández") or something else.

Thanks

**Comment by realthunder** [comment] 2021-03-10 13:41
Oh, my FreeCAD repo's issue page is actually more appropriate. But here also can. I'll investigate.

**Comment by realthunder** [comment] 2021-03-11 03:56
I can't reproduce the problem. Are you using MacOS native saving file dialog, something like below? Can you please try the tips [here](https://github.com/realthunder/FreeCAD_assembly3/issues/506#issuecomment-793310500) to wipe out your recent file list information and try save again?

![Screenshot from 2021-03-11 11-48-19](https://user-images.githubusercontent.com/1207888/110733162-72d58800-8260-11eb-881d-a282f533d819.png)

Note that when I save the file, the Start Page tooltip shows the absolute path of the file.

![Screenshot from 2021-03-11 11-48-37](https://user-images.githubusercontent.com/1207888/110733215-8aad0c00-8260-11eb-849c-b18d8efbcc2f.png)

**Comment by luzpaz** [comment] 2021-08-05 00:38
Closing as a dupe of #506

**Closed by luzpaz** 2021-08-05 00:38 UTC
