### ISSUE TITLE
Start page error message about missing thumbnail file

### ISSUE THREAD

**Issue by adrianinsaval** [realthunder/FreeCAD_assembly3#506] opened 2021-03-09 01:36 UTC
Start page shows an annoying error message about missing thumbnails:
![Untitled](https://user-images.githubusercontent.com/36372335/110404155-1fdfb300-805d-11eb-9dfc-fe55a72e4a32.png)
![Untitled2](https://user-images.githubusercontent.com/36372335/110404905-7bf70700-805e-11eb-90c4-422e2ac7b982.png)

The message appears many times with different file names. If I leave the start page open the messages randomly appears again after some time, I don't know what triggers this. FreeCAD master shows no errors.
I probably wiped the temp folder before that but I don't really remember.

**Comment by adrianinsaval** [comment] 2021-03-09 01:45
Just noticed one of the messages complains about a missing image from start workbench not just another thumbnail from temp:
![Untitled3](https://user-images.githubusercontent.com/36372335/110405204-faec3f80-805e-11eb-969c-51d518bedd09.png)
That one I definitively didn't delete.

**Comment by realthunder** [comment] 2021-03-09 03:08
I've also seen this type of error some time ago. But it goes away before I got a chance to inspect it. And I can't reproduce it anymore. The above referenced commit simply change the warning dialog into a report view log message, just in case it happens again.

Meanwhile, as a work around, you can manually remove all MRU entries in (BaseApp/Preferences/RecentFiles) and set `RecentFiles` to 0, using parameter editor. Then restart FreeCAD and see if recent file list has been cleared.

**Comment by luzpaz** [comment] 2021-08-05 00:38
@realthunder can this be closed?

**Comment by realthunder** [comment] 2021-08-05 12:22
Yeah, most likely fixed by [this](https://github.com/realthunder/FreeCAD/commit/16d876c8eea7c34d91b589626deaf222896e9c60).

**Closed by realthunder** 2021-08-05 12:22 UTC
