### ISSUE TITLE
Unable to delete quotes in sketch

### ISSUE THREAD

**Issue by Anducalliew** [realthunder/FreeCAD_assembly3#557] opened 2021-04-04 15:34 UTC
With latest daily release(FreeCAD-asm3-Daily-Conda-Py3-Qt5-20210328-glibc2.12-x86_64.AppImage) I'm not able to delete a quote in a sketch.

Open new file
Create a sketch
Draw a single line
Add a horizontal quote

I can't delete the created quote with delete, nor with dx click, delete.
If I save the file and open it with standard freecad 0.19 I can delete the quote.

**Comment by kevenwyld** [comment] 2021-04-04 20:14
By quote do you mean constraint?  Can you delete any constraints in a sketch?  I can't seem to delete anything except lines/points in the latest daily.  Even by selecting it in the constraint box and right click -> deleting.  It works as expected in previous versions.

**Comment by Anducalliew** [comment] 2021-04-05 10:40
Yes, I mean constraints. I can't delete any type of constraint.

**Comment by realthunder** [comment] 2021-04-05 10:42
This is duplicate of realthunder/FreeCAD#123. And it has been fixed already. I'll make a new release soon.

**Comment by Anducalliew** [comment] 2021-04-05 13:33
Thanks and sorry for the duplicate!

**Closed** 2021-04-05 13:37 UTC
